char OWN_IP_ADDRESS[] ICACHE_RODATA_ATTR = "192.168.0.23"; // 22 - LED projector, 23 - Halogen projector
char OWN_NETMASK[] ICACHE_RODATA_ATTR = "255.255.255.0";
char OWN_GETAWAY_ADDRESS[] ICACHE_RODATA_ATTR = "192.168.0.1";
char SERVER_IP_ADDRESS[] ICACHE_RODATA_ATTR = "192.168.0.2";
char ACCESS_POINT_NAME[] ICACHE_RODATA_ATTR = "SAMSUNG";
char ACCESS_POINT_PASSWORD[] ICACHE_RODATA_ATTR = "x>vZf8bqX]l-qg%";
char DEVICE_NAME[] ICACHE_RODATA_ATTR = "Halogen projectors"; // "LED projector", "Halogen projector"

#define SERVER_PORT 80
#define SERVER_IP_ADDRESS_1 192
#define SERVER_IP_ADDRESS_2 168
#define SERVER_IP_ADDRESS_3 0
#define SERVER_IP_ADDRESS_4 2
